version = 1

[[annotations]]
path = [
    "PKGBUILD",
    ".SRCINFO",
    "*.changelog",
    "fix-offline-uv-build.patch",
    "no-update.patch",
    "strip-formatter-deps.patch",
    "strip-python-pip-system-certs.patch",
    "strip-type-checking-deps.patch",
    "test.patch",
]
SPDX-FileCopyrightText = "Arch Linux contributors"
SPDX-License-Identifier = "0BSD"
